steamate/chatmate/utils.py
steamate/chatmate/views.py
steamate/requirements.txt

csv 파일 교체로 인한 성능 챗봇 성능 개선,
csv 파일의 용량으로 인한 utils.py 코드 수정
필요한 라이브러리(pandas) 추가
없음
requirments.txt
views.py
utils.py
/data

벡터db 데이터 교체로 인한 챗봇 성능 개선

---

steamate/chatmate/views.py

views.py 예외처리 및 응답 구조 개선
404처리 및 예외처리
없음
views.py
없음
없음

:recycle: views.py 예외처리 및 응답 구조 개선

---

steamate/account/models.py
steamate/account/serializers.py
steamate/account/views.py

close #17 
serializers.py 수정
model 수정

:bug: 비밀번호 확인 수정

---

steamate/chatmate/utils_v2.py
steamate/chatmate/views.py

rag 입력 증강 방식 추가로 인해 성능 개선
- 입력 속도 저하
- 답변 품질 향상
자세한 개선 과정은 추가 설명에서 후술
없음
수정 : views.py
삭제 : utils.py
추가 : utils_v2.py
없음
Query2doc 방식
- 쿼리 변환 중에서도 HyDE와, Query2doc가 있지만 복잡한 질문("구스구스덕을 좋아하는 여성 3명에서 4명이 즐기기 좋은 캐주얼 게임 추천좀” 등)을 해석하기 위해 Query2doc 적용시도
TOC(Table of Contents) 방식:
- Query2doc 방식으로 생성된 문서를 TOC 방식으로 llm모델을 통해 다시 쿼리문으로 분해
RQ-RAG 방식:
- 분해된 쿼리문으로 쿼리문 마다 3개씩 벡터 검색 후 복수벡터 제거 후 프롬프팅에 삽입
결과
- 질문의 이해도 급상승
- 질문과 무관한 게임 추천 빈도 급격히 감소
- 답변 시간 급증
보완점
- 아직 위 방식들을 기본적으로만 구현했지 세부적으로는 구현하지 못함
- 더 정확하게 위 방식들을 구현 해야함
근거 논문(https://arxiv.org/html/2402.19473v6)
- Retrieval-Augmented Generation for AI-Generated Content: A Survey

:zap: 입력 증강 방식 추가로 인한 챗봇 성능 개선

---

frontend/public/manifest.json
frontend/src/App.js
frontend/src/context/AuthContext.js
frontend/src/pages/ChatMate.js
frontend/src/pages/Home.js
frontend/src/pages/Login.js
frontend/src/pages/MyPage.js

챗 세션 조회, 추가, 삭제
대화내역 수정, 삭제 
구현
없음
ChatMate.js
없음
없음

:link: 챗봇 부가기능 api 연결

---

frontend/src/App.js
frontend/src/components/Header.js
frontend/src/context/AuthContext.js
frontend/src/pages/Login.js
frontend/src/pages/SteamCallback.js
frontend/src/pages/SteamSignup.js
steamate/account/views.py
steamate/config/settings.py

- Steam 회원가입 페이지를 생성하여 회원가입 API 연결
- Steam 로그인 API 연결
없음
- frontend/
- steam 회원가입과 로그인을 위한 `SteamCallback.js`, `SteamSignup.js` 파일 추가
- Login.js : Steam 로그인 API 연결
- AuthContext.js : Steam 로그인의 JWT 설정
- steamte/
- config/setting.py : 8000포트를 3000포트로 수정
- account/views.py : `openid.return_to` 링크 수정
- Steam 회원가입
- 스팀회원 가입 시 프로필에 라이브러리가 안 가져오는 문제가 생겼습니다. 이 부분은 이슈로 생성하여 해결하겠습니다.

🔗 Steam 회원가입/로그인 API 연결

---

frontend/src/pages/ChatMate.js

메세지가 쌓이면 채팅입력창이 밀리는 버그 수정
여백 개선
스크롤 자동 이동 추가
#30 
ChatMate.js

:bug: :zap: 메세지가 쌓이면 채팅입력창이 밀리는 버그 수정, 여백 개선, 스크롤 자동 이동

---

docker-compose.yaml
nginx/Dockerfile
nginx/nginx.conf
steamate/config/settings.py

:rocket: 배포

---

steamate/config/settings.py

:recycle: ALLOWED_HOSTS 및 CSRF,CORS_ALLOWED 추가

---

steamate/account/urls.py
steamate/account/utils.py
steamate/account/views.py
steamate/config/settings.py

회원가입, 연동 시 라이브러리 불러오는 과정을 삭제
라이브러리를 가져오는 API 생성
없음
라이브러리 불러올 때 상황을 세분화

:recycle: Steam 라이브러리 불러오는 기능 분할

---

docker-compose.yaml
nginx/nginx.conf
steamate/config/settings.py

:rocket: AWS 로드밸런스 배포

---

steamate/account/views.py

이메일 인증 Front URL 수정, 오탈자 수정
없음
이메일 인증 Front URL 수정, 오탈자 수정

:beers: 오탈자 수정

---

steamate/chatmate/utils_v3.py
steamate/chatmate/views.py

입력 강화에서 기존에선 잘못된 가상문서를 생성하던 것을 제대로 생성하게 개선
가상문서 쿼리 분해도 잘못된 방식이던걸 제대로 생성하게 개선
프롬프팅을 편하게 픽스할 수 있게 일단 한글로 전부 수정(마지막에 영어로 바꿀 예정)
없음
수정 views.py
버전 업 utils_2.py -> utils_3.py

:zap: 입력 강화 프롬프팅 수정으로 인한 성능 대폭 개선

---

steamate/chatmate/utils_v3.py

:recycle: 개발용 검증 코드 삭제

---

.github/workflows/main.yml

Github Action 도입

---

steamate/chatmate/utils_v5.py

vectorDB 임베딩 컬럼 추가
프롬프팅에 게임 URL 이미지 URL 추가
없음
삭제 utils_v4.py
추가 utils_v5.py

vectorDB 임베딩 컬럼 추가, 프롬프트 게임 URL 이미지 URL 추가

---

steamate/account/tasks.py
steamate/account/utils.py
steamate/requirements.txt

:bug: 급한 수정

---

steamate/account/tasks.py

처음 이후로 라이브러리 동기화를 할 때, 에러 발생하는 것을 수정
없음
__appid를 _id로만 변경을 했습니다.

:bug: 연속으로 가져올 때 에러 수정

---

steamate/pickmate/utils.py
steamate/pickmate/views.py

- front에서 필요한 데이터가 있어서 데이터 추가했습니다.
없음
- utils.py : DB에서 데이터를 가져오는 함수 추가
- views.py : 데이터를 가져와서 json 형식으로 response 할 수 있는 코드 추가

:recycle: 게임 정보 추가하여 response 데이터 변경

---

steamate/chatmate/consumers.py
steamate/chatmate/utils_v5.py

기존에 했던 게임에 대한 정보 추가(appid + 플레이타임)
프롬프트 변경으로 인한 성능 향상
없음
utils_v5.py
consumers.py

기존에 했던 게임에 대한 정보 추가

---

steamate/chatmate/consumers.py
steamate/chatmate/utils_v5.py

선호 게임 파라미터 추가 및 프롬프트 추가로 인한 챗봇 답변 성능 향상
없음
consumers.py
utils_v5.py

선호 게임 파라미터 추가 및 프롬프트 추가로 인한 챗봇 답변 성능 향상

---

nginx/nginx.conf

배포 상태에서 PATCH 메서드가 허용이 되지 않아 nginx 설정 변경
없음

:bug: 배포에서 patch 요청이 허용되지 않은 상황 수정

---

.gitignore

- gitignore에 학습용파일을 추가해서 git에서 권한을 제외합니다.
없음
.gitignore

:see_no_evil: ML 학습용 파일 추가

---

steamate/chatmate/consumers.py
steamate/chatmate/history.py
steamate/chatmate/prompt.py
steamate/chatmate/utils_v5.py
steamate/chatmate/vectorstore.py
steamate/chatmate/views.py
steamate/config/settings.py

utils_v5.py 리팩토링(코드 분리)
메세지 수정 파라미터 누락 디버깅
환경변수 재활용성 개선
없음
utils_v5.py 코드 분리
추가
- history.py
- prompt.py
- routing.py
- vectorstore.py
수정
- settings.py
- views.py
- consumers.py

utils_v5.py 리팩토링(코드 분리), 메세지 수정 파라미터 누락 디버깅

---

README.md

- README 업데이트 했습니다
없음
- README

:memo: README 업데이트

---

LICENSE

:page_facing_up: License

---

steamate/Dockerfile.wsgi

:beers: mange -> manage.py

---

steamate/chatmate/prompt.py
steamate/chatmate/utils_v5.py

게임 정보 검색 함수 설명 및 멀티턴 대화 개선
없음
utils_v5.py
prompt.py

게임 정보 검색 함수 설명 및 멀티턴 대화 개선

---

.github/workflows/main.yml

CI/CD 상에서 캐시가 남지 않게 test 하게 설정
없음

:hammer: main.yml 수정

---

.github/workflows/main.yml

:beers: 오타 수정

---

steamate/Dockerfile.asgi

asig docker 실행 시 캐시를 남기지 않고 라이브러리 설치
없음

:recycle: asig docker 실행 시 캐시를 남기지 않고 라이브러리 설치

---

steamate/chatmate/consumers.py
steamate/chatmate/prompt.py
steamate/chatmate/utils_v5.py

프롬프트 수정
챗봇 응답 처리 개선
없음
consumers.py
utils.py
prompt.py

챗봇 응답 처리 개선

---

steamate/Dockerfile.asgi
steamate/chatmate/consumers.py
steamate/chatmate/prompt.py
steamate/chatmate/utils_v5.py

- 프롬프트 개선
- gpt-4o-mini 파라미터 temperature=0 -> temperature=0.2 로 변경

Develop 변경 사항 main merge
